---
- name: Install Podman packages
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present

- name: Get podman repos from git
  ansible.builtin.git:
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(omit) }}"
    gpg_whitelist: "{{ item.gpg_whitelist | default(omit) }}"
    key_file: "{{ item.key_file | default(omit) }}"
    recursive: "{{ item.recursive | default(omit) }}"
    reference: "{{ item.reference | default(omit) }}"
    refspec: "{{ item.refspec | default(omit) }}"
    remote: "{{ item.remote | default(omit) }}"
    repo: "{{ item.repo }}"
    verify_commit: "{{ item.verify_commit | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ podman_git_repos }}"

- name: Manage podman images
  containers.podman.podman_image:
    build: "{{ item.build | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    name: "{{ item.name }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    tag: "{{ item.tag | default(omit) }}"
  loop: "{{ podman_images }}"
  tags:
    - podman_images

- name: Manage pods
  containers.podman.podman_pod:
    name: "{{ item.name }}"
    publish: "{{ item.publish | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ podman_pods }}"
  tags:
    - podman_pods

- name: Manage containers
  containers.podman.podman_container:
    annotation: "{{ item.annotation | default(omit) }}"
    arch: "{{ item.arch | default(omit) }}"
    attach: "{{ item.attach | default(omit) }}"
    authfile: "{{ item.authfile | default(omit) }}"
    blkio_weight: "{{ item.blkio_weight | default(omit) }}"
    blkio_weight_device: "{{ item.blkio_weight_device | default(omit) }}"
    cap_add: "{{ item.cap_add | default(omit) }}"
    cap_drop: "{{ item.cap_drop | default(omit) }}"
    cgroup_conf: "{{ item.cgroup_conf | default(omit) }}"
    cgroup_parent: "{{ item.cgroup_parent | default(omit) }}"
    cgroupns: "{{ item.cgroupns | default(omit) }}"
    cgroups: "{{ item.cgroups | default(omit) }}"
    chrootdirs: "{{ item.chrootdirs | default(omit) }}"
    cidfile: "{{ item.cidfile | default(omit) }}"
    cmd_args: "{{ item.cmd_args | default(omit) }}"
    command: "{{ item.command | default(omit) }}"
    conmon_pidfile: "{{ item.conmon_pidfile | default(omit) }}"
    cpu_period: "{{ item.cpu_period | default(omit) }}"
    cpu_quota: "{{ item.cpu_quota | default(omit) }}"
    cpu_rt_period: "{{ item.cpu_rt_period | default(omit) }}"
    cpu_rt_runtime: "{{ item.cpu_rt_runtime | default(omit) }}"
    cpu_shares: "{{ item.cpu_shares | default(omit) }}"
    cpus: "{{ item.cpus | default(omit) }}"
    cpuset_cpus: "{{ item.cpuset_cpus | default(omit) }}"
    cpuset_mems: "{{ item.cpuset_mems | default(omit) }}"
    debug: "{{ item.debug | default(omit) }}"
    decryption_key: "{{ item.decryption_key | default(omit) }}"
    delete_depend: "{{ item.delete_depend | default(omit) }}"
    delete_time: "{{ item.delete_time | default(omit) }}"
    delete_volumes: "{{ item.delete_volumes | default(omit) }}"
    detach: "{{ item.detach | default(omit) }}"
    detach_keys: "{{ item.detach_keys | default(omit) }}"
    device: "{{ item.device | default(omit) }}"
    device_cgroup_rule: "{{ item.device_cgroup_rule | default(omit) }}"
    device_read_bps: "{{ item.device_read_bps | default(omit) }}"
    device_read_iops: "{{ item.device_read_iops | default(omit) }}"
    device_write_bps: "{{ item.device_write_bps | default(omit) }}"
    device_write_iops: "{{ item.device_write_iops | default(omit) }}"
    dns: "{{ item.dns | default(omit) }}"
    dns_option: "{{ item.dns_option | default(omit) }}"
    dns_search: "{{ item.dns_search | default(omit) }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    env_file: "{{ item.env_file | default(omit) }}"
    env_host: "{{ item.env_host | default(omit) }}"
    env_merge: "{{ item.env_merge | default(omit) }}"
    etc_hosts: "{{ item.etc_hosts | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
    expose: "{{ item.expose | default(omit) }}"
    force_delete: "{{ item.force_delete | default(omit) }}"
    force_restart: "{{ item.force_restart | default(omit) }}"
    generate_systemd: "{{ item.generate_systemd | default(omit) }}"
    gidmap: "{{ item.gidmap | default(omit) }}"
    gpus: "{{ item.gpus | default(omit) }}"
    group_add: "{{ item.group_add | default(omit) }}"
    group_entry: "{{ item.group_entry | default(omit) }}"
    health_startup_cmd: "{{ item.health_startup_cmd | default(omit) }}"
    health_startup_interval: "{{ item.health_startup_interval | default(omit) }}"
    health_startup_retries: "{{ item.health_startup_retries | default(omit) }}"
    health_startup_success: "{{ item.health_startup_success | default(omit) }}"
    health_startup_timeout: "{{ item.health_startup_timeout | default(omit) }}"
    healthcheck: "{{ item.healthcheck | default(omit) }}"
    healthcheck_failure_action: "{{ item.healthcheck_failure_action | default(omit) }}"
    healthcheck_interval: "{{ item.healthcheck_interval | default(omit) }}"
    healthcheck_retries: "{{ item.healthcheck_retries | default(omit) }}"
    healthcheck_start_period: "{{ item.healthcheck_start_period | default(omit) }}"
    healthcheck_timeout: "{{ item.healthcheck_timeout | default(omit) }}"
    hooks_dir: "{{ item.hooks_dir | default(omit) }}"
    hostname: "{{ item.hostname | default(omit) }}"
    hostuser: "{{ item.hostuser | default(omit) }}"
    http_proxy: "{{ item.http_proxy | default(omit) }}"
    image: "{{ item.image | default(omit) }}"
    image_strict: "{{ item.image_strict | default(omit) }}"
    image_volume: "{{ item.image_volume | default(omit) }}"
    init: "{{ item.init | default(omit) }}"
    init_ctr: "{{ item.init_ctr | default(omit) }}"
    init_path: "{{ item.init_path | default(omit) }}"
    interactive: "{{ item.interactive | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    ip6: "{{ item.ip6 | default(omit) }}"
    ipc: "{{ item.ipc | default(omit) }}"
    kernel_memory: "{{ item.kernel_memory | default(omit) }}"
    label: "{{ item.label | default(omit) }}"
    label_file: "{{ item.label_file | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    log_level: "{{ item.log_level | default(omit) }}"
    log_opt: "{{ item.log_opt | default(omit) }}"
    mac_address: "{{ item.mac_address | default(omit) }}"
    memory: "{{ item.memory | default(omit) }}"
    memory_reservation: "{{ item.memory_reservation | default(omit) }}"
    memory_swap: "{{ item.memory_swap | default(omit) }}"
    memory_swappiness: "{{ item.memory_swappiness | default(omit) }}"
    mount: "{{ item.mount | default(omit) }}"
    name: "{{ item.name }}"
    network: "{{ item.network | default(omit) }}"
    network_aliases: "{{ item.network_aliases | default(omit) }}"
    no_healthcheck: "{{ item.no_healthcheck | default(omit) }}"
    no_hosts: "{{ item.no_hosts | default(omit) }}"
    oom_kill_disable: "{{ item.oom_kill_disable | default(omit) }}"
    oom_score_adj: "{{ item.oom_score_adj | default(omit) }}"
    os: "{{ item.os | default(omit) }}"
    passwd: "{{ item.passwd | default(omit) }}"
    passwd_entry: "{{ item.passwd_entry | default(omit) }}"
    personality: "{{ item.personality | default(omit) }}"
    pid: "{{ item.pid | default(omit) }}"
    pid_file: "{{ item.pid_file | default(omit) }}"
    pids_limit: "{{ item.pids_limit | default(omit) }}"
    platform: "{{ item.platform | default(omit) }}"
    pod: "{{ item.pod | default(omit) }}"
    pod_id_file: "{{ item.pod_id_file | default(omit) }}"
    preserve_fd: "{{ item.preserve_fd | default(omit) }}"
    preserve_fds: "{{ item.preserve_fds | default(omit) }}"
    privileged: "{{ item.privileged | default(omit) }}"
    publish: "{{ item.publish | default(omit) }}"
    publish_all: "{{ item.publish_all | default(omit) }}"
    pull: "{{ item.pull | default(omit) }}"
    quadlet_dir: "{{ item.quadlet_dir | default(omit) }}"
    quadlet_filename: "{{ item.quadlet_filename | default(omit) }}"
    quadlet_options: "{{ item.quadlet_options | default(omit) }}"
    rdt_class: "{{ item.rdt_class | default(omit) }}"
    read_only: "{{ item.read_only | default(omit) }}"
    read_only_tmpfs: "{{ item.read_only_tmpfs | default(omit) }}"
    recreate: "{{ item.recreate | default(omit) }}"
    requires: "{{ item.requires | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    restart_time: "{{ item.restart_time | default(omit) }}"
    retry: "{{ item.retry | default(omit) }}"
    retry_delay: "{{ item.retry_delay | default(omit) }}"
    rm: "{{ item.rm | default(omit) }}"
    rmi: "{{ item.rmi | default(omit) }}"
    rootfs: "{{ item.rootfs | default(omit) }}"
    sdnotify: "{{ item.sdnotify | default(omit) }}"
    seccomp_policy: "{{ item.seccomp_policy | default(omit) }}"
    secrets: "{{ item.secrets | default(omit) }}"
    security_opt: "{{ item.security_opt | default(omit) }}"
    shm_size: "{{ item.shm_size | default(omit) }}"
    shm_size_systemd: "{{ item.shm_size_systemd | default(omit) }}"
    sig_proxy: "{{ item.sig_proxy | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    stop_signal: "{{ item.stop_signal | default(omit) }}"
    stop_time: "{{ item.stop_time | default(omit) }}"
    stop_timeout: "{{ item.stop_timeout | default(omit) }}"
    subgidname: "{{ item.subgidname | default(omit) }}"
    subuidname: "{{ item.subuidname | default(omit) }}"
    sysctl: "{{ item.sysctl | default(omit) }}"
    systemd: "{{ item.systemd | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    timezone: "{{ item.timezone | default(omit) }}"
    tls_verify: "{{ item.tls_verify | default(omit) }}"
    tmpfs: "{{ item.tmpfs | default(omit) }}"
    tty: "{{ item.tty | default(omit) }}"
    uidmap: "{{ item.uidmap | default(omit) }}"
    ulimit: "{{ item.ulimit | default(omit) }}"
    umask: "{{ item.umask | default(omit) }}"
    unsetenv: "{{ item.unsetenv | default(omit) }}"
    unsetenv_all: "{{ item.unsetenv_all | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    userns: "{{ item.userns | default(omit) }}"
    uts: "{{ item.uts | default(omit) }}"
    variant: "{{ item.variant | default(omit) }}"
    volume: "{{ item.volume | default(omit) }}"
    volumes_from: "{{ item.volumes_from | default(omit) }}"
    workdir: "{{ item.workdir | default(omit) }}"
  loop: "{{ podman_containers }}"
  no_log: true
  tags:
    - podman_containers
  register: __podman_containers
  notify:
    - Restart quadlet containers

- name: Configure podman-auto-update systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: "{{ podman_auto_update_enabled }}"
    state: "{{ podman_auto_update_state }}"
  loop: "{{ podman_auto_update_systemd_units }}"
