---
- name: Get podman repos from git
  ansible.builtin.git:
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(omit) }}"
    gpg_whitelist: "{{ item.gpg_whitelist | default(omit) }}"
    key_file: "{{ item.key_file | default(omit) }}"
    recursive: "{{ item.recursive | default(omit) }}"
    reference: "{{ item.reference | default(omit) }}"
    refspec: "{{ item.refspec | default(omit) }}"
    remote: "{{ item.remote | default(omit) }}"
    repo: "{{ item.repo }}"
    verify_commit: "{{ item.verify_commit | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
  loop: "{{ podman_git_repos }}"

- name: Manage podman images
  containers.podman.podman_image:
    build: "{{ item.build | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    name: "{{ item.name }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    tag: "{{ item.tag | default(omit) }}"
  loop: "{{ podman_images }}"
  tags:
    - podman_images

- name: Manage pods
  containers.podman.podman_pod:
    name: "{{ item.name }}"
    publish: "{{ item.publish | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ podman_pods }}"
  tags:
    - podman_pods

- name: Manage containers
  containers.podman.podman_container:
    command: "{{ item.command | default(omit) }}"
    dns: "{{ item.dns | default(omit) }}"
    dns_option: "{{ item.dns_option | default(omit) }}"
    dns_search: "{{ item.dns_search | default(omit) }}"
    entrypoint: "{{ item.entrypoint | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    etc_hosts: "{{ item.etc_hosts | default(omit) }}"
    image: "{{ item.image }}"
    ip: "{{ item.ip | default(omit) }}"
    name: "{{ item.name }}"
    pod: "{{ item.pod | default(omit) }}"
    recreate: "{{ item.recreate | default(omit) }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    rm: "{{ item.rm | default(omit) }}"
    sysctl: "{{ item.sysctl | default(omit) }}"
    volume: "{{ item.volume | default(omit) }}"
  loop: "{{ podman_containers }}"
  no_log: true
  tags:
    - podman_containers
