---
- name: Manage podman images
  containers.podman.podman_image:
    build: "{{ item.build | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    name: "{{ item.name }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    tag: "{{ item.tag | default(omit) }}"
  loop: "{{ podman_images }}"

- name: Manage pods
  containers.podman.podman_pod:
    name: "{{ item.name }}"
    publish: "{{ item.publish | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ podman_pods }}"

- name: Manage containers
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    restart_policy: "{{ item.restart_policy | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    pod: "{{ item.pod | default(omit) }}"
    recreate: "{{ item.recreate | default(omit) }}"
    volume: "{{ item.volume | default(omit) }}"
  loop: "{{ podman_containers }}"
  no_log: true
